"""empty message

Revision ID: a422e9f540da
Revises: c0b88dd7efe3
Create Date: 2023-01-13 15:43:47.074459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a422e9f540da'
down_revision = 'c0b88dd7efe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               comment='账号',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               comment='密码',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               comment='邮箱唯一',
               existing_nullable=False)
        batch_op.alter_column('join_time',
               existing_type=mysql.DATETIME(),
               comment='添加时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('join_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='添加时间',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='邮箱唯一',
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='账号',
               existing_nullable=False)

    # ### end Alembic commands ###
