"""empty message

Revision ID: af440010d19f
Revises: 5b1f4953ab73
Create Date: 2023-01-17 15:51:23.166931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af440010d19f'
down_revision = '5b1f4953ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id主键'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='评论创建时间'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='问题外键'),
    sa.Column('author_id', sa.Integer(), nullable=True, comment='评论者外键'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='发布者外键',
               existing_comment='发布者ID外键',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='发布者ID外键',
               existing_comment='发布者外键',
               existing_nullable=True)

    op.drop_table('answer')
    # ### end Alembic commands ###
