"""empty message

Revision ID: ec992460c7c2
Revises: a422e9f540da
Create Date: 2023-01-16 11:21:59.004673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec992460c7c2'
down_revision = 'a422e9f540da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('captcha', sa.String(length=100), nullable=False, comment='验证码'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
